# Generated by Django 4.0.1 on 2022-01-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sold_actuel', models.DecimalField(decimal_places=3, max_digits=6)),
                ('derniere_creditation', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=3, max_digits=6)),
                ('numero', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Envoie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=3, max_digits=6)),
                ('numero', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numero', models.CharField(max_length=9)),
                ('montant', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
