# Generated by Django 4.0.1 on 2022-01-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historique', '0002_alter_creditation_derniere_creditation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditation',
            name='derniere_creditation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='creditation',
            name='sold_actuel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='montant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='envoie',
            name='montant',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant',
            field=models.IntegerField(),
        ),
    ]
